=== kumarabhishek0809/CoreJava/documents/event.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="event">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="headers">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:short" name="businessKey"/>
              <xs:element type="xs:string" name="employeeLoginId"/>
              <xs:element type="xs:short" name="employeeNumber"/>
              <xs:element type="xs:dateTime" name="eventCreatedDate"/>
              <xs:element type="xs:long" name="eventCreatedTimeInNanos"/>
              <xs:element type="xs:string" name="eventId"/>
              <xs:element type="xs:string" name="eventType"/>
              <xs:element type="xs:byte" name="rootIdentifier"/>
              <xs:element name="sourceChannel">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="id"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:byte" name="systemInfoUserId"/>
              <xs:element type="xs:float" name="version"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="body">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="establishmentApplicationStatusEvent">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="applicationActionReason">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:short" name="applicationActionReasons" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:short" name="applicationNo"/>
                    <xs:element type="xs:string" name="comments"/>
                    <xs:element name="estabApplicationAction">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:long" name="correlationId"/>
                          <xs:element name="estabApplicationActionDocuments" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="documentId">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:short" name="id"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element type="xs:string" name="documentReasonId"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:byte" name="status"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== kumarabhishek0809/CoreJava/documents/event.xml
<?xml version="1.0" encoding="UTF-8"?>
<event xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="event.xsd">
  <headers>
    <businessKey>0</businessKey>
    <employeeLoginId>employeeLoginId</employeeLoginId>
    <employeeNumber>0</employeeNumber>
    <eventCreatedDate>eventCreatedDate</eventCreatedDate>
    <eventCreatedTimeInNanos>0</eventCreatedTimeInNanos>
    <eventId>eventId</eventId>
    <eventType>eventType</eventType>
    <rootIdentifier>0</rootIdentifier>
    <sourceChannel>
      <id>0</id>
    </sourceChannel>
    <systemInfoUserId>0</systemInfoUserId>
    <version>0</version>
  </headers>
  <body>
    <establishmentApplicationStatusEvent>
      <applicationNo>0</applicationNo>
      <comments>comments</comments>
      <status>0</status>
    </establishmentApplicationStatusEvent>
  </body>
</event>
